
title: Kunologist's Tech-house
email: kunologist@foxmail.com
description: >- # this means to ignore newlines until "baseurl:"
  A personal blog storing all the rarely-documented stuff.
  100% Originality!

domain: "gennadiyev.github.io"
url: "https://gennadiyev.github.io" # the base hostname & protocol for your site
baseurl: "/Gennadiyev/" # the subpath of the site

permalink: /:year-:month/:title
timezone:

favicon: /assets/img/favicon.ico

user:
  name: Kun
  pic: /assets/img/cat.jpg
  picAlt: "Kat?"
  job: Undergraduate @ SJTU
  # aboutme: true # comment this out if you don't need the 'about' page.

exclude:
  - README.md
  - LICENSE
  - github

defaults:
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      comment: false

markdown_ext: "markdown,mkdown,mkdn,mkd,md"
markdown: kramdown 

# Filtering Content
show_drafts: null
limit_posts: 0
future:      false
unpublished: false
